#!/usr/bin/python

#TODO:application documentation
import argparse
from metapackage import NSControl

#application command line execution...
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-d','--description',help="Description for the meta-package.")
    parser.add_argument('-m','--maintainer',help="Maintainer for the meta-package {Name} <e-mail address>")
    parser.add_argument('name',help="Name of the meta-package to build.")
    parser.add_argument('version',help='Package version to build.')
    parser.add_argument('packages',metavar='PKG',type=str,nargs='+',help='package to add to meta-package')
    args = parser.parse_args()
        
    ctrl = NSControl()
    ctrl.setName(args.name)
    if(args.description is not None):
        ctrl.setDescription(args.description)
    if(args.maintainer is not None):
        ctrl.setMaintainer(args.maintainer)
    ctrl.setPackages(args.packages)
    ctrl.setVersion(args.version)
    ctrl.build()
    